version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: flux-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:your_secure_root_password}
      MYSQL_DATABASE: ${DB_NAME:flux}
      MYSQL_USER: ${DB_USERNAME:flux_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:your_secure_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./flux_back/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - flux-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: flux-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:your_redis_password}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flux-network

  # Backend Application
  backend:
    build:
      context: ./flux_back
      dockerfile: Dockerfile
    container_name: flux-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:flux}
      DB_USERNAME: ${DB_USERNAME:flux_user}
      DB_PASSWORD: ${DB_PASSWORD:your_secure_password}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD:your_redis_password}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:https://yourdomain.com}
    ports:
      - "8080:8080"
    volumes:
      - ./flux_back/logs:/app/logs
    depends_on:
      - mysql
      - redis
    networks:
      - flux-network

  # Frontend Application
  frontend:
    build:
      context: ./flux_for
      dockerfile: Dockerfile
    container_name: flux-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - backend
    networks:
      - flux-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  flux-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16